version: '3.8'

services:
  server:
    build:
      context: ./server
    networks:
      rede-sisop-2:
        ipv4_address: 172.20.0.254  # Definindo um IP fixo
    ports:
      - "9000:8080/udp"              # 9000 acessa o container | 8080 porta da aplicação

networks:
  rede-sisop-2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16      # Definindo a sub-rede manualmente
