services:
  server:
    build:
      context: ./server
    networks:
      rede-sisop-2:
        ipv4_address: 172.20.0.254  # Definindo um IP fixo
    ports:
      - "4000:4000/udp"
    stdin_open: true
    tty: true

  client1:
    build:
      context: ./client  # Diretório onde está o Dockerfile do cliente
    networks:
      - rede-sisop-2
    stdin_open: true
    tty: true

  client2:
    build:
      context: ./client  # Diretório onde está o Dockerfile do cliente
    networks:
      - rede-sisop-2
    stdin_open: true
    tty: true
    
  client3:
    build:
      context: ./client  # Diretório onde está o Dockerfile do cliente
    networks:
      - rede-sisop-2
    stdin_open: true
    tty: true

networks:
  rede-sisop-2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16      # Definindo a sub-rede manualmente
